#!/usr/bin/env python3
"""Supplementary Fig. 8 redraw: single-nucleus RNA-seq QC and C6/C9/C10 markers.

Inputs
  Source Data sheets Fig.2g-SF14_cells (78,193 nuclei: UMAP, cluster, nCount/nFeature),
  SF14c_sample_counts, SF14d_QC_flow (loaded into ../SF7/sd.pkl);
  C6_C9_C10_top120_markers_with_annotation.tsv (03_V3/03_figure3/03_single; generated by
  inspect_C6_C9_C10_marker_function.R, ranked by marker_rank_score within cluster).
Panel d replaces the former QC funnel (no nucleus was removed at any step; the counts are now
stated in panel c and the legend). Marker rule: per cluster, the first five genes in the source
ranking (marker_rank_score descending) that carry a non-empty product annotation.
The marker table only reports in-cluster versus all-other-nuclei statistics, so the dot plot
compares these two groups rather than all 20 clusters.
"""
import pickle
from pathlib import Path

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
MM = 1 / 25.4
DARK = "#242A30"
SAMPLES = [("FL", 95), ("FL", 125), ("FL", 185), ("TN", 95), ("TN", 125), ("TN", 185)]
SCOL = {("FL", 95): "#9ED3CB", ("FL", 125): "#2A9D8F", ("FL", 185): "#155C54",
        ("TN", 95): "#F0B3B3", ("TN", 125): "#D95F5F", ("TN", 185): "#8E2E2E"}
# --- beautify 2026-09-24: scheme A (fix/beautify/common/palA.py); stage shades = 45 % tint / full / 60 % shade ---
import sys  # noqa: E402
sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "beautify/common"))
import palA  # noqa: E402


def _shade(h, f=0.6):
    h = h.lstrip("#")
    return "#%02X%02X%02X" % tuple(round(int(h[i:i + 2], 16) * f) for i in (0, 2, 4))


SCOL = {("FL", 95): palA.tint(palA.FL, 0.45), ("FL", 125): palA.FL, ("FL", 185): _shade(palA.FL),
        ("TN", 95): palA.tint(palA.TN, 0.45), ("TN", 125): palA.TN, ("TN", 185): _shade(palA.TN)}

mpl.rcParams.update({
    "font.family": "Arial", "font.size": 7, "axes.labelsize": 7, "axes.titlesize": 7,
    "xtick.labelsize": 6, "ytick.labelsize": 6, "legend.fontsize": 6, "axes.linewidth": 0.6,
    "xtick.major.width": 0.6, "ytick.major.width": 0.6, "xtick.major.size": 2.5, "ytick.major.size": 2.5,
    "axes.unicode_minus": True, "mathtext.fontset": "custom", "mathtext.rm": "Arial",
    "mathtext.it": "Arial:italic", "mathtext.bf": "Arial:bold", "pdf.fonttype": 42, "svg.fonttype": "none",
})


def clean(ax):
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.set_axisbelow(True)


# ---------------- enh_sn_pop 2026-09-25: panels i-k (bulk replication, doublets, clustering stability)
RES = HERE.parent / "res"
STAGES = ["0d", "15d", "35d", "50d", "65d", "80d", "95d", "110d", "125d", "140d", "155d", "170d", "185d",
          "12h", "24h", "36h", "48h", "60h", "72h"]
FLC, TNC = palA.FL, palA.TN


def _stars(q):
    return "***" if q < 0.001 else "**" if q < 0.01 else "*" if q < 0.05 else "n.s."


def draw_validation(fig):
    per = pd.read_csv(RES / "bulk_scores_per_library.tsv", sep="\t")
    per = per[per.marker_set == "published_top50"]
    tst = pd.read_csv(RES / "bulk_FL_vs_TN_tests.tsv", sep="\t")
    tst = tst[(tst.marker_set == "published_top50") & (tst.score == "mean_z")]
    g = fig.add_gridspec(1, 6, left=0.085, right=0.985, top=0.148, bottom=0.047, wspace=0.62,
                         width_ratios=[1.25, 1.25, 1.25, 1.0, 0.95, 0.95])
    out = []
    x = np.arange(len(STAGES))
    for j, k in enumerate(("C9", "C6", "C10")):
        ax = fig.add_subplot(g[0, j])
        d = per[per.cluster == k]
        for gt, col in (("FL", FLC), ("TN", TNC)):
            mm = d[d.genotype == gt].groupby("stage").mean_z.agg(["mean", "std"]).reindex(STAGES)
            ax.fill_between(x, mm["mean"] - mm["std"], mm["mean"] + mm["std"], color=col, alpha=0.25, lw=0)
            ax.plot(x, mm["mean"], color=col, lw=0.9, marker="o", ms=1.6, label=gt)
        for st in ("95d", "125d", "185d"):
            i = STAGES.index(st); q = tst[(tst.cluster == k) & (tst.stage == st)].BH.iloc[0]
            ax.text(i, 1.0, _stars(q), ha="center", va="bottom", fontsize=4.6, transform=ax.get_xaxis_transform(),
                    rotation=90 if q >= 0.05 else 0)
            ax.axvspan(i - 0.4, i + 0.4, color="#EEEEEE", zorder=0, lw=0)
        ax.axvline(12.5, color="#999999", lw=0.5, ls="--")
        ax.set_xticks([0, 6, 12, 18], ["0", "95", "185 d", "72 h"], fontsize=5)
        ax.set_xlim(-0.6, 18.6)
        lo, hi = d.mean_z.min(), d.mean_z.max()
        ax.set_ylim(lo - 0.15, hi + 0.15)
        ax.set_title(f"{k} marker score (bulk)", pad=9, fontsize=6)
        if j == 0:
            ax.set_ylabel("Mean z-score of\n50 marker genes", fontsize=6)
            ax.legend(frameon=False, fontsize=5, loc="upper left", handlelength=1.2, borderaxespad=0.1)
        ax.tick_params(labelsize=5)
        clean(ax)
        out.append((ax, "i") if j == 0 else None)
    out = [o for o in out if o]
    # j: doublets
    dbl = pd.read_csv(RES / "scrublet_calls_v4rate.tsv.gz", sep="\t", index_col=0)
    pc = dbl.groupby("seurat_clusters").call.mean().mul(100)
    ax = fig.add_subplot(g[0, 3])
    order = pc.sort_values().index
    cols = [{9: FLC, 6: TNC, 10: _shade(TNC)}.get(c, "#BBBBBB") for c in order]
    ax.bar(range(len(order)), pc[order].values, color=cols, width=0.8)
    for n_, c in enumerate([c for c in order if c in (6, 9, 10)]):
        i = list(order).index(c)
        ax.annotate(f"C{c}", (i, pc[c]), xytext=(i - 4 + 3 * n_, pc.max() * (0.62 + 0.14 * n_)), fontsize=5,
                    ha="center", arrowprops=dict(arrowstyle="-", lw=0.4, color="#555555"))
    ax.axhline(dbl.call.mean() * 100, color="#555555", lw=0.6, ls="--")
    ax.set_xticks([])
    ax.set_xlabel("20 clusters (ranked)", fontsize=5.5)
    ax.set_ylabel("Predicted doublets (%)", fontsize=6)
    ax.set_title("Scrublet doublets", pad=9, fontsize=6)
    ax.set_ylim(0, pc.max() * 1.25)
    ax.tick_params(labelsize=5)
    clean(ax)
    out.append((ax, "j"))
    # k: stability
    st = pd.read_csv(RES / "cluster_stability.tsv", sep="\t")
    rs = st[st.analysis == "resolution"].sort_values("resolution")
    sb = st[st.analysis == "subsample80"]
    xs = list(range(len(rs))) + [len(rs) + 0.4]
    xl = [f"{r:g}" for r in rs.resolution] + ["80%"]
    CC = {"C9": FLC, "C6": TNC, "C10": _shade(TNC)}
    for jj, (met, yl) in enumerate((("share_in_best", "Nuclei kept together"),
                                    ("best_FLfrac185", "FL share of 185-d nuclei"))):
        ax = fig.add_subplot(g[0, 4 + jj])
        for k, col in CC.items():
            v = rs[f"{k}_{met}"].values
            ax.plot(xs[:-1], v, color=col, lw=0.9, marker="o", ms=1.8, label=k)
            b = sb[f"{k}_{met}"].values
            ax.errorbar([xs[-1]], [np.median(b)], yerr=[[np.median(b) - b.min()], [b.max() - np.median(b)]],
                        color=col, marker="s", ms=2, lw=0.8, capsize=1)
        ax.set_xticks(xs, xl, fontsize=4.8, rotation=90)
        ax.set_xlabel("Resolution / subsample", fontsize=5.5)
        ax.set_ylim(0, 1.05)
        ax.set_ylabel(yl, fontsize=6)
        ax.tick_params(labelsize=5)
        if jj == 0:
            ax.set_title("Clustering stability", pad=9, fontsize=6, loc="left")
            ax.legend(frameon=False, fontsize=5, loc="lower left", handlelength=1.2, borderaxespad=0.1)
            out.append((ax, "k"))
        else:
            ax.set_title("of best-matching cluster", pad=2, fontsize=5)
        clean(ax)
    return out


def slabel(v, t):
    return f"{v} {t} d"


d = pickle.load(open(HERE.parents[2] / "redraw/SF7/sd.pkl", "rb"))
cells = d["Fig.2g-SF14_cells"].copy()
cells["key"] = list(zip(cells.variety, cells.timepoint))
counts = d["SF14c_sample_counts"]
qc = d["SF14d_QC_flow"]
assert len(cells) == 78193 and counts.nuclei.sum() == 78193 and (qc.Removed_nuclei == 0).all()

mk = pd.read_csv(HERE / "C6_C9_C10_top120_markers_with_annotation.tsv", sep="\t")
mk["product"] = mk["product"].fillna("").astype(str).str.strip()
sel = []
for cl in ("C6", "C9", "C10"):
    s = mk[(mk.cluster == cl) & (mk["product"] != "")].sort_values("marker_rank_score", ascending=False)
    sel.append(s.head(5))
sel = pd.concat(sel).reset_index(drop=True)
# Display names: eggNOG free-text descriptions shortened to a family/function name (mapping exported).
SHORT = {
    "Belongs to the membrane-bound acyltransferase family": "Membrane-bound O-acyltransferase family",
    "Belongs to the 1-acyl-sn-glycerol-3-phosphate acyltransferase family": "1-Acylglycerol-3-phosphate acyltransferase",
    "Belongs to the mannose-6-phosphate isomerase type 1 family": "Mannose-6-phosphate isomerase type 1",
    "Transmembrane amino acid transporter protein": "Transmembrane amino acid transporter",
    "Pyruvate dehydrogenase E1 component subunit": "Pyruvate dehydrogenase E1 subunit",
    "PCO_ADO": "PCO_ADO-domain protein",
    "alcohol dehydrogenase": "Alcohol dehydrogenase",
}
def short(t):
    if t.startswith("first, biotin carboxylase"):
        return "Biotin carboxylase (ACCase subunit)"
    return SHORT.get(t, t)
sel["display_name"] = sel["product"].map(short)

fig = plt.figure(figsize=(180 * MM, 268 * MM))
g0 = fig.add_gridspec(1, 2, left=0.06, right=0.97, top=0.9741, bottom=0.7890, wspace=0.55)
g1 = fig.add_gridspec(1, 2, left=0.07, right=0.80, top=0.7307, bottom=0.5764, wspace=1.35,
                      width_ratios=[0.85, 0.75])
g2 = fig.add_gridspec(1, 2, left=0.07, right=0.97, top=0.5056, bottom=0.4055, wspace=0.25)
g3 = fig.add_gridspec(1, 2, left=0.07, right=0.93, top=0.3330, bottom=0.2054, wspace=0.55)

# a: UMAP by sample
rng = np.random.default_rng(3)
idx = rng.permutation(len(cells))
ax = fig.add_subplot(g0[0, 0])
cc = [SCOL[k] for k in cells.key.values[idx]]
ax.scatter(cells.umap_1.values[idx], cells.umap_2.values[idx], s=0.15, c=cc, lw=0, rasterized=True)
for k in SAMPLES:
    ax.scatter([], [], s=12, color=SCOL[k], label=slabel(*k))
ax.legend(frameon=False, loc="upper left", bbox_to_anchor=(1.0, 1.0), markerscale=1, handletextpad=0.2)
ax.set_xticks([])
ax.set_yticks([])
ax.set_xlabel("UMAP 1")
ax.set_ylabel("UMAP 2")
ax.set_title("Nuclei by sample (Harmony-integrated)", pad=3)
ax_a = ax

# b: UMAP by cluster
ax = fig.add_subplot(g0[0, 1])
cl_num = cells.seurat_clusters.astype(int).values
cmap = plt.get_cmap("tab20")
ax.scatter(cells.umap_1.values[idx], cells.umap_2.values[idx], s=0.15, c=[cmap(i % 20) for i in cl_num[idx]],
           lw=0, rasterized=True)
cent = cells.groupby("seurat_clusters")[["umap_1", "umap_2"]].median()
for c, r in cent.iterrows():
    ax.text(r.umap_1, r.umap_2, f"C{int(c)}", fontsize=5.5, ha="center", va="center", fontweight="bold",
            bbox=dict(boxstyle="round,pad=0.12", fc="white", ec="none", alpha=0.75))
ax.set_xticks([])
ax.set_yticks([])
ax.set_xlabel("UMAP 1")
ax.set_ylabel("UMAP 2")
ax.set_title(f"{len(cells):,} nuclei in 20 clusters", pad=3)
ax_b = ax

# c: nuclei per sample
ax = fig.add_subplot(g1[0, 0])
cnt = counts.set_index(["variety", "timepoint"]).nuclei
ys = [cnt[k] for k in SAMPLES]
ax.bar(range(6), ys, color=[SCOL[k] for k in SAMPLES], width=0.7)
for i, y in enumerate(ys):
    ax.text(i, y + 250, f"{y:,}", ha="center", va="bottom", fontsize=5.3)
ax.set_xticks(range(6), [slabel(*k) for k in SAMPLES], rotation=45, ha="right")
ax.set_ylabel("Nuclei retained")
ax.set_ylim(0, max(ys) * 1.15)
ax.set_title("Nuclei per library (total 78,193)", pad=3)
clean(ax)
ax_c = ax

# d: marker dot plot (in-cluster vs all other nuclei)
ax = fig.add_subplot(g1[0, 1])
n = len(sel)
yy = np.arange(n)[::-1]
vmax = float(np.ceil(max(sel.mean_in.max(), sel.mean_out.max())))
norm = mpl.colors.Normalize(0, vmax)
cm = plt.get_cmap("Reds")
for xpos, pcol, mcol in ((0, "pct_in", "mean_in"), (1, "pct_out", "mean_out")):
    ax.scatter(np.full(n, xpos), yy, s=sel[pcol] * 70 + 0.5, c=cm(norm(sel[mcol])), edgecolor="#555555",
               linewidth=0.3, zorder=3)
lab = []
for _, r in sel.iterrows():
    prod = r["display_name"]
    lab.append(f"{prod} ({r.gene_id.replace('evm.TU.', '')})")
ax.set_yticks(yy, lab, fontsize=5.3)
ax.set_xticks([0, 1], ["In cluster", "Other nuclei"])
ax.set_xlim(-0.5, 1.5)
ax.set_ylim(-0.7, n - 0.3)
for k, cl in enumerate(("C6", "C9", "C10")):
    top = n - 1 - 5 * k
    ax.text(1.62, top - 2, cl, fontsize=7, fontweight="bold", va="center", ha="left",
            transform=ax.transData, clip_on=False)
    if k:
        ax.axhline(top + 0.5, color="#CCCCCC", lw=0.5)
ax.set_title("Top annotated markers of C6, C9 and C10", pad=3)
for sp in ("top", "right"):
    ax.spines[sp].set_visible(False)
cax = fig.add_axes([0.90, 0.6723, 0.012, 0.0500])
cb = fig.colorbar(mpl.cm.ScalarMappable(norm=norm, cmap=cm), cax=cax)
cb.set_label("Mean\nexpression", fontsize=5.5)
cb.ax.tick_params(labelsize=5)
for i, p in enumerate((0.25, 0.5, 0.9)):
    fig.axes[-1]  # keep colourbar
    ax.scatter([], [], s=p * 70 + 0.5, color="#BBBBBB", edgecolor="#555555", lw=0.3, label=f"{int(p*100)}%")
ax.legend(title="Nuclei\nexpressing", frameon=False, loc="lower left", bbox_to_anchor=(1.28, -0.02),
          fontsize=5.3, title_fontsize=5.5, labelspacing=0.9, handletextpad=0.3)
ax_d = ax

# e, f: violins
for j, (col, ttl, yl) in enumerate((("nCount_RNA", "UMI counts per nucleus", r"log$_{10}$(UMI + 1)"),
                                    ("nFeature_RNA", "Genes detected per nucleus", r"log$_{10}$(genes + 1)"))):
    ax = fig.add_subplot(g2[0, j])
    data = [np.log10(cells.loc[cells.key == k, col].values + 1) for k in SAMPLES]
    vp = ax.violinplot(data, positions=range(6), widths=0.8, showextrema=False)
    for body, k in zip(vp["bodies"], SAMPLES):
        body.set_facecolor(SCOL[k])
        body.set_edgecolor("#555555")
        body.set_linewidth(0.4)
        body.set_alpha(0.9)
    q1 = [np.percentile(v, 25) for v in data]
    q3 = [np.percentile(v, 75) for v in data]
    md = [np.median(v) for v in data]
    ax.vlines(range(6), q1, q3, color=DARK, lw=2.2)
    ax.scatter(range(6), md, s=5, color="white", zorder=3)
    ax.set_xticks(range(6), [slabel(*k) for k in SAMPLES], rotation=45, ha="right")
    ax.set_ylabel(yl)
    ax.set_title(ttl, pad=3)
    clean(ax)
    if j == 0:
        ax_e = ax
    else:
        ax_f = ax

# g: UMI vs genes hexbin
ax = fig.add_subplot(g3[0, 0])
hb = ax.hexbin(cells.nCount_RNA, cells.nFeature_RNA, gridsize=60, xscale="log", yscale="log", bins="log",
               cmap=mpl.colors.LinearSegmentedColormap.from_list("seqW", palA.SEQ_WARM[1:]), mincnt=1, linewidths=0)
# redraw2: scheme-A warm sequential (was viridis; its yellow top was the brightest mark on the page)
ax.set_xlabel("UMI counts per nucleus")
ax.set_ylabel("Genes detected per nucleus")
ax.set_title("UMI counts versus genes detected", pad=3)
cb = fig.colorbar(hb, ax=ax, pad=0.02, fraction=0.05)
cb.set_label("Nuclei", fontsize=6)
cb.ax.tick_params(labelsize=6)  # beautify: exponent 3.5 -> 4.2 pt, as axis ticks
clean(ax)
ax_g = ax

# h: cluster composition (fraction of each library's nuclei)
ax = fig.add_subplot(g3[0, 1])
cells["slab"] = [slabel(*k) for k in cells.key]
SL = [slabel(*k) for k in SAMPLES]
tab = pd.crosstab(cells.seurat_clusters.astype(int), cells.slab)[SL]
frac = tab / tab.sum(axis=0) * 100
im = ax.pcolormesh(np.arange(7) - 0.5, np.arange(21) - 0.5, frac.values,
                   cmap="Blues", vmin=0,
                   vmax=float(np.ceil(frac.values.max() / 5) * 5), edgecolors="white", linewidth=0.4)
ax.set_xlim(-0.5, 5.5)
ax.set_ylim(19.5, -0.5)
for sp in ax.spines.values():
    sp.set_visible(False)
ax.tick_params(length=0)
# redraw2: vector cells with white separators (was a bitmap); same Blues scale as before
ax.set_yticks(range(20), [f"C{i}" for i in frac.index], fontsize=5.2)
ax.set_xticks(range(6), [slabel(*k) for k in SAMPLES], rotation=45, ha="right")
ax.set_ylabel("Cluster")
ax.set_title("Cluster composition of each library", pad=3)
cb = fig.colorbar(im, ax=ax, pad=0.02, fraction=0.05)
cb.set_label("Library nuclei (%)", fontsize=6)
cb.ax.tick_params(labelsize=5)
ax_h = ax

NEW_AXES = draw_validation(fig)
for ax, s in [(ax_a, "a"), (ax_b, "b"), (ax_c, "c"), (ax_d, "d"), (ax_e, "e"), (ax_f, "f"), (ax_g, "g"),
              (ax_h, "h")] + NEW_AXES:
    bb = ax.get_position()
    dx = -0.30 if s == "d" else (-0.045 if s in "ijk" else -0.055)
    fig.text(bb.x0 + dx, bb.y1 + 0.008, s, fontsize=palA.LETTER_PT, fontweight="bold", va="bottom")

out = HERE / "out"  # enh_sn_pop copy
out.mkdir(exist_ok=True)
for ext in ("pdf", "png"):
    fig.savefig(out / f"Supplementary_Fig_08.{ext}", dpi=600, facecolor="white")
sel[["cluster", "gene_id", "product", "display_name", "marker_rank_score", "mean_in", "mean_out", "log2fc_mean", "pct_in",
     "pct_out"]].to_csv(out / "SF8d_marker_dotplot.tsv", sep="\t", index=False)
frac.round(4).to_csv(out / "SF8h_cluster_fraction_by_library.tsv", sep="\t")
viol = pd.DataFrame([dict(sample=slabel(*k), metric=c, median=np.median(cells.loc[cells.key == k, c]),
                          q1=np.percentile(cells.loc[cells.key == k, c], 25),
                          q3=np.percentile(cells.loc[cells.key == k, c], 75))
                     for k in SAMPLES for c in ("nCount_RNA", "nFeature_RNA")])
viol.to_csv(out / "SF8ef_per_library_summary.tsv", sep="\t", index=False)
print(sel[["cluster", "gene_id", "product", "display_name", "pct_in", "pct_out", "mean_in", "mean_out"]].to_string())
print(viol.to_string())
